# Generated by Django 3.0.4 on 2020-04-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_client', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Id del cliente')),
                ('name_cliente', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('RUT_cliente', models.CharField(max_length=100, verbose_name='RUT del Cliente')),
                ('categoria_cliente', models.CharField(max_length=100, verbose_name='Categoria de Cliente')),
                ('name_contact', models.CharField(max_length=100, verbose_name='Nombre contacto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name_cliente'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.CharField(choices=[('NUEVA ORDEN', 'NUEVA ORDEN'), ('AUMENTO DE ORDEN', 'AUMENTO DE ORDEN'), ('MODIFICACION DE ORDEN', 'MODIFICACION DE ORDEN')], default='NUEVA ORDEN', max_length=100, verbose_name='Tipo de Solicitud')),
                ('aumentoModificacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='En caso de aumento o modificación ingrese el  N° DE ORDEN')),
                ('documentoTributario', models.CharField(choices=[('Boleta', 'Boleta'), ('Factura', 'Factura')], default='Factura', max_length=30, verbose_name='Documento Tributario')),
                ('alimentacion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=100, verbose_name='Incluye Alimentación')),
                ('Bandera_enviado', models.IntegerField(choices=[(1, 'Guardado'), (2, 'Enviado'), (3, 'Aprobado'), (4, 'Pendiente con observaciones'), (5, 'Rechazar')], default=1, verbose_name='Enviado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'DetalleOrden',
                'verbose_name_plural': 'DetalleOrdenes',
                'ordering': ['client'],
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Articulo')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('detalle', models.CharField(blank=True, max_length=30, null=True, verbose_name='Detalle')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('datos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.DetalleOrden', verbose_name='Datos')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
