# Generated by Django 3.0.4 on 2020-04-06 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_client', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Id del cliente')),
                ('name_cliente', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('RUT_cliente', models.CharField(max_length=100, verbose_name='RUT del Cliente')),
                ('categoria_cliente', models.CharField(max_length=100, verbose_name='Categoria de Cliente')),
                ('name_contact', models.CharField(max_length=100, verbose_name='Nombre contacto')),
                ('tipo_contact', models.CharField(max_length=100, verbose_name='Tipo de contacto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name_cliente'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.CharField(choices=[('NUEVA ORDEN', 'NUEVA ORDEN'), ('AUMENTO DE ORDEN', 'AUMENTO DE ORDEN'), ('MODIFICACION DE ORDEN', 'MODIFICACION DE ORDEN')], default='NUEVA ORDEN', max_length=100, verbose_name='Tipo de Solicitud')),
                ('aumentoModificacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='En caso de aumento o modificación ingrese el  N° DE ORDEN')),
                ('documentoTributario', models.CharField(choices=[('Boleta', 'Boleta'), ('Factura', 'Factura')], default='Factura', max_length=30, verbose_name='Documento Tributario')),
                ('alimentacion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=100, verbose_name='Incluye Alimentación')),
                ('Bandera_enviado', models.IntegerField(choices=[(1, 'Guardado'), (2, 'Enviado'), (3, 'Aprobado'), (4, 'Pendiente con observaciones'), (5, 'Rechazar')], default=1, verbose_name='Enviado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sales_program', models.CharField(max_length=100, verbose_name='Sales program')),
                ('coment_ecomer', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Comentarios')),
                ('coment_eteso', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Comentarios')),
                ('num_orden', models.IntegerField(blank=True, null=True, verbose_name='Numero de orden generada')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.Cliente', verbose_name='Cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DetalleOrden',
                'verbose_name_plural': 'DetalleOrdenes',
                'ordering': ['client'],
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Item')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad')),
                ('desde', models.DateTimeField(verbose_name='Fecha desde')),
                ('hasta', models.DateTimeField(verbose_name='Fecha hasta')),
                ('valor_bruto', models.IntegerField(verbose_name='Precio bruto')),
                ('detalle', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='Notas')),
                ('datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.DetalleOrden', verbose_name='Datos')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
