# Generated by Django 2.2.5 on 2020-03-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cliente', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('RUT_cliente', models.CharField(max_length=100, verbose_name='RUT del Cliente')),
                ('categoria_cliente', models.CharField(max_length=100, verbose_name='Categoria de Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_contacto', models.CharField(max_length=100, verbose_name='Registro de Contacto en Sistema')),
                ('nombreApellido', models.CharField(max_length=100, verbose_name='Nombre y Apellido Contacto')),
                ('tipo_contacto', models.CharField(max_length=100, verbose_name='RUT del Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='null', max_length=100, verbose_name='Dirección')),
                ('comuna', models.CharField(default='null', max_length=100, verbose_name='Comuna')),
                ('ciudad', models.CharField(default='null', max_length=100, verbose_name='Ciudad')),
                ('provincia', models.CharField(default='null', max_length=100, verbose_name='Provincia')),
                ('zip_code', models.CharField(default='null', max_length=100, verbose_name='ZIP Code')),
                ('pais', models.CharField(default='null', max_length=100, verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.CharField(choices=[('NUEVA ORDEN', 'NUEVA ORDEN'), ('AUMENTO DE ORDEN', 'AUMENTO DE ORDEN'), ('MODIFICACION DE ORDEN', 'MODIFICACION DE ORDEN')], default='NUEVA ORDEN', max_length=100, verbose_name='Tipo de Solicitud')),
                ('aumentoModificacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='En caso de aumento o modificación ingrese el  N° DE ORDEN')),
                ('documentoTributario', models.CharField(choices=[('Boleta', 'Boleta'), ('Factura', 'Factura')], default='Factura', max_length=30, verbose_name='Documento Tributario')),
                ('alimentacion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=100, verbose_name='Incluye Alimentación')),
                ('Bandera_enviado', models.CharField(choices=[('Guardado', 'Guardado'), ('Enviado', 'Enviado'), ('Aprobado', 'Aprobado'), ('Pendiente con observaciones', 'Pendiente con observaciones')], default='Guardado', max_length=30, verbose_name='Enviado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.Cliente')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.Contacto')),
            ],
            options={
                'verbose_name': 'DetalleOrden',
                'verbose_name_plural': 'DetalleOrdenes',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.Direccion'),
        ),
    ]
