# Generated by Django 2.2.5 on 2020-03-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='Bandera_enviado',
            field=models.CharField(choices=[(1, 'Guardado'), (2, 'Enviado'), (3, 'Aprobado'), (4, 'Pendiente con observaciones')], default=1, max_length=30, verbose_name='Enviado'),
        ),
    ]
