# Generated by Django 3.0.4 on 2020-04-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_contact',
            field=models.CharField(choices=[(1, 'Cliente (Comercial)'), (2, 'Bill To (Facturación y Boletas)'), (3, 'Ship To (Sólo Envio)')], default='Cliente (Comercial)', max_length=100, verbose_name='Tipo de contacto'),
        ),
    ]
