# Generated by Django 3.0.4 on 2020-04-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20200406_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='categoria_cliente',
            field=models.CharField(choices=[(1, 'EMPRESAS'), (2, 'COLEGIOS'), (3, 'UNIVERSIDADES'), (4, 'FUNCIONARIOS'), (5, 'PERSONAS')], default='EMPRESAS', max_length=100, verbose_name='Categoria de Cliente'),
        ),
    ]
