# Generated by Django 3.0.4 on 2020-04-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_auto_20200406_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='categoria_cliente',
            field=models.IntegerField(choices=[(1, 'EMPRESAS'), (2, 'COLEGIOS'), (3, 'UNIVERSIDADES'), (4, 'FUNCIONARIOS'), (5, 'PERSONAS')], default='EMPRESAS', verbose_name='Categoria de Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_contact',
            field=models.IntegerField(choices=[(1, 'Cliente (Comercial)'), (2, 'Bill To (Facturación y Boletas)'), (3, 'Ship To (Sólo Envio)')], default='Cliente (Comercial)', verbose_name='Tipo de contacto'),
        ),
    ]
