# Generated by Django 3.0.4 on 2020-04-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_auto_20200407_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='Bandera_enviado',
            field=models.IntegerField(choices=[(1, 'Guardado'), (2, 'Enviado'), (3, 'Aprobado'), (4, 'Pendiente con observaciones'), (5, 'Rechazar'), (6, 'Aprobado tesoreria'), (7, 'Pendiente con observaciones tesoreria'), (8, 'Rechazar tesoreria')], default=1, verbose_name='Enviado'),
        ),
    ]
