# Generated by Django 3.0.4 on 2020-04-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_auto_20200415_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
